name: EBeam Tests 

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:     
  ebeam-lib-pcell-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull siepic_klayout image
        run: docker pull ghcr.io/jasminabrar/siepic_ebeam_pdk/siepic_klayout:master-latest
     
      - name: Run docker container from image
        run: docker run -itd --name ebeam_test -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --security-opt label=type:container_runtime_t ghcr.io/jasminabrar/siepic_ebeam_pdk/siepic_klayout:master-latest

      - name: Copy pymacros folder to docker container and set EBeam_Lib_PCellTests.py to be executable
        run: |
                docker cp $GITHUB_WORKSPACE/klayout/EBeam/pymacros ebeam_test:/home/pymacros
                docker exec ebeam_test chmod +x /home/pymacros/EBeam_Lib_PCellTests.py

      - name: Install coverage inside the container
        run: |
                docker exec ebeam_test /usr/bin/python3 -m pip install pytest 
                docker exec ebeam_test /usr/bin/python3 -m pip install klayout

      - name: Run KLayout Python script inside container and capture exit code
        run: docker exec ebeam_test pytest /home/pymacros/EBeam_Lib_PCellTests.py --cov=/home/pymacros  || echo "KLAYOUT_EXIT_CODE=$?" >> $GITHUB_ENV
        # run: docker exec ebeam_test /usr/bin/python3 /home/pymacros/run_tests.py || echo "KLAYOUT_EXIT_CODE=$?" >> $GITHUB_ENV
        # shell: /usr/bin/bash -e {0}

        # run: docker exec ebeam_test klayout -zz -r pymacros/EBeam_Lib_PCellTests.py || echo "KLAYOUT_EXIT_CODE=$?" >> $GITHUB_ENV
        # continue-on-error: true

      - name: Stop container and remove it 
        run: |
                docker stop ebeam_test
                docker rm ebeam_test
        
      - name: Upload coverage reports to Codecov.
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Fail job if exit code is non-zero
        run: |
                if [ $KLAYOUT_EXIT_CODE -ne 0 ]; then
                        echo "KLayout exited with non-zero exit code"
                        exit 1
                fi
