name: Get latest version tag from siepic repos

on:
  push:
    branches:
      - '**'

jobs:
  get_version:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install jq -y

      - name: get latest version of siepic ebeam pdk
        id: get-version
        run: |
          # Get the latest release version from the target repository
          VERSION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/SiEPIC/SiEPIC_EBeam_PDK/releases/latest" \
            | jq -r .tag_name)

          echo "Latest version is $VERSION"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}